# Site settings
title: Primary Jekyll Setup
email: akkrisan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my go-to build when setting up a new Jekyll site. It features
  HAML, SASS, and my other preferred tools.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://krisan.me" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  akkrisan

# Build settings
markdown: kramdown
